import type { Bilingual } from "@/types/i18n";
import rafiKotImage from "@/features/landing/assets/images/doctors/doctor-rafi-kot.jpg";
import mattiasLarssonImage from "@/features/landing/assets/images/doctors/doctor-mattias-larsson.jpg";

export interface Doctor {
  id: string;
  name: Bilingual;
  role: Bilingual;
  specialty: Bilingual;
  location: Bilingual;
  nationality: Bilingual;
  languages: Bilingual;
  image: string;
}

export const doctors: Doctor[] = [
  {
    id: "rafi-kot",
    name: { en: "Dr. Rafi Kot", vi: "Bác sĩ Rafi Kot" },
    role: {
      en: "Executive Director, Founder Thao Dien",
      vi: "Giám đốc điều hành, Người sáng lập Thảo Điền",
    },
    specialty: { en: "Family Medicine", vi: "Y học gia đình" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Israeli", vi: "Israel" },
    languages: {
      en: "English, Polish, German, Hebrew, Vietnamese, Russian",
      vi: "Tiếng Anh, Tiếng Ba Lan, Tiếng Đức, Tiếng Do Thái, Tiếng Việt, Tiếng Nga",
    },
    image: rafiKotImage,
  },
  {
    id: "mattias-larsson",
    name: { en: "Dr. Mattias Larsson", vi: "Bác sĩ Mattias Larsson" },
    role: { en: "Medical Director", vi: "Giám đốc Y khoa" },
    specialty: { en: "Pediatrics", vi: "Nhi khoa" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "Swedish", vi: "Thụy Điển" },
    languages: {
      en: "Swedish, English, German, Vietnamese",
      vi: "Tiếng Thụy Điển, Tiếng Anh, Tiếng Đức, Tiếng Việt",
    },
    image: mattiasLarssonImage,
  },
  {
    id: "nguyen-van-an",
    name: { en: "Dr. Nguyen Van An", vi: "Bác sĩ Nguyễn Văn An" },
    role: { en: "Senior Cardiologist", vi: "Bác sĩ Tim mạch cấp cao" },
    specialty: { en: "Cardiology", vi: "Tim mạch" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: rafiKotImage,
  },
  {
    id: "tran-thi-mai",
    name: { en: "Dr. Tran Thi Mai", vi: "Bác sĩ Trần Thị Mai" },
    role: { en: "Head of Pediatrics", vi: "Trưởng khoa Nhi" },
    specialty: { en: "Pediatrics", vi: "Nhi khoa" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: {
      en: "Vietnamese, English, French",
      vi: "Tiếng Việt, Tiếng Anh, Tiếng Pháp",
    },
    image: mattiasLarssonImage,
  },
  {
    id: "david-miller",
    name: { en: "Dr. David Miller", vi: "Bác sĩ David Miller" },
    role: { en: "Consultant Dermatologist", vi: "Bác sĩ Chuyên khoa Da liễu" },
    specialty: { en: "Dermatology", vi: "Da liễu" },
    location: { en: "Da Nang", vi: "Đà Nẵng" },
    nationality: { en: "American", vi: "Mỹ" },
    languages: { en: "English, Vietnamese", vi: "Tiếng Anh, Tiếng Việt" },
    image: rafiKotImage,
  },
  {
    id: "elena-rostova",
    name: { en: "Dr. Elena Rostova", vi: "Bác sĩ Elena Rostova" },
    role: { en: "Orthopedic Surgeon", vi: "Phẫu thuật viên Chỉnh hình" },
    specialty: { en: "Orthopedics", vi: "Chỉnh hình" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Russian", vi: "Nga" },
    languages: { en: "Russian, English", vi: "Tiếng Nga, Tiếng Anh" },
    image: mattiasLarssonImage,
  },
  {
    id: "le-hoang-long",
    name: { en: "Dr. Le Hoang Long", vi: "Bác sĩ Lê Hoàng Long" },
    role: { en: "Ophthalmology Specialist", vi: "Chuyên gia Mắt" },
    specialty: { en: "Ophthalmology", vi: "Nhãn khoa" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: {
      en: "Vietnamese, English, Japanese",
      vi: "Tiếng Việt, Tiếng Anh, Tiếng Nhật",
    },
    image: rafiKotImage,
  },
  {
    id: "sato-kenji",
    name: { en: "Dr. Sato Kenji", vi: "Bác sĩ Sato Kenji" },
    role: { en: "Neurologist", vi: "Bác sĩ Thần kinh" },
    specialty: { en: "Neurology", vi: "Thần kinh" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Japanese", vi: "Nhật Bản" },
    languages: {
      en: "Japanese, English, Vietnamese",
      vi: "Tiếng Nhật, Tiếng Anh, Tiếng Việt",
    },
    image: mattiasLarssonImage,
  },
  {
    id: "pham-quynh-nga",
    name: { en: "Dr. Pham Quynh Nga", vi: "Bác sĩ Phạm Quỳnh Nga" },
    role: { en: "General Practitioner", vi: "Bác sĩ Tổng quát" },
    specialty: { en: "General Medicine", vi: "Y học tổng quát" },
    location: { en: "Da Nang", vi: "Đà Nẵng" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: rafiKotImage,
  },
  {
    id: "michael-smith",
    name: { en: "Dr. Michael Smith", vi: "Bác sĩ Michael Smith" },
    role: { en: "Telehealth Director", vi: "Giám đốc Y tế Từ xa" },
    specialty: { en: "Telemedicine", vi: "Y tế từ xa" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "British", vi: "Anh" },
    languages: { en: "English, Spanish", vi: "Tiếng Anh, Tiếng Tây Ban Nha" },
    image: mattiasLarssonImage,
  },
  {
    id: "hoang-vinh-phuc",
    name: { en: "Dr. Hoang Vinh Phuc", vi: "Bác sĩ Hoàng Vinh Phúc" },
    role: { en: "Cardiologist", vi: "Bác sĩ Tim mạch" },
    specialty: { en: "Cardiology", vi: "Tim mạch" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: rafiKotImage,
  },
  {
    id: "vu-thao-vy",
    name: { en: "Dr. Vu Thao Vy", vi: "Bác sĩ Vũ Thảo Vy" },
    role: { en: "Pediatric Specialist", vi: "Chuyên gia Nhi khoa" },
    specialty: { en: "Pediatrics", vi: "Nhi khoa" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: mattiasLarssonImage,
  },
  {
    id: "claire-dupont",
    name: { en: "Dr. Claire Dupont", vi: "Bác sĩ Claire Dupont" },
    role: { en: "Dermatologist", vi: "Bác sĩ Da liễu" },
    specialty: { en: "Dermatology", vi: "Da liễu" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "French", vi: "Pháp" },
    languages: {
      en: "French, English, Vietnamese",
      vi: "Tiếng Pháp, Tiếng Anh, Tiếng Việt",
    },
    image: rafiKotImage,
  },
  {
    id: "bui-duc-dung",
    name: { en: "Dr. Bui Duc Dung", vi: "Bác sĩ Bùi Đức Dũng" },
    role: { en: "Orthopedic Surgeon", vi: "Bác sĩ Phẫu thuật Chỉnh hình" },
    specialty: { en: "Orthopedics", vi: "Chỉnh hình" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: mattiasLarssonImage,
  },
  {
    id: "ngo-thanh-tam",
    name: { en: "Dr. Ngo Thanh Tam", vi: "Bác sĩ Ngô Thanh Tâm" },
    role: { en: "Ophthalmologist", vi: "Bác sĩ Nhãn khoa" },
    specialty: { en: "Ophthalmology", vi: "Nhãn khoa" },
    location: { en: "Da Nang", vi: "Đà Nẵng" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: rafiKotImage,
  },
  {
    id: "hans-mueller",
    name: { en: "Dr. Hans Mueller", vi: "Bác sĩ Hans Mueller" },
    role: { en: "Senior Neurologist", vi: "Bác sĩ Thần kinh cấp cao" },
    specialty: { en: "Neurology", vi: "Thần kinh" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "German", vi: "Đức" },
    languages: { en: "German, English", vi: "Tiếng Đức, Tiếng Anh" },
    image: mattiasLarssonImage,
  },
  {
    id: "phan-minh-tuan",
    name: { en: "Dr. Phan Minh Tuan", vi: "Bác sĩ Phan Minh Tuấn" },
    role: { en: "General Practitioner", vi: "Bác sĩ Tổng quát" },
    specialty: { en: "General Medicine", vi: "Y học tổng quát" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: rafiKotImage,
  },
  {
    id: "giulia-rossi",
    name: { en: "Dr. Giulia Rossi", vi: "Bác sĩ Giulia Rossi" },
    role: { en: "Telemedicine Consultant", vi: "Cố vấn Y tế Từ xa" },
    specialty: { en: "Telemedicine", vi: "Y tế từ xa" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Italian", vi: "Ý" },
    languages: {
      en: "Italian, English, French",
      vi: "Tiếng Ý, Tiếng Anh, Tiếng Pháp",
    },
    image: mattiasLarssonImage,
  },
  {
    id: "dang-quoc-viet",
    name: { en: "Dr. Dang Quoc Viet", vi: "Bác sĩ Đặng Quốc Việt" },
    role: { en: "Cardiologist", vi: "Bác sĩ Tim mạch" },
    specialty: { en: "Cardiology", vi: "Tim mạch" },
    location: { en: "Da Nang", vi: "Đà Nẵng" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: rafiKotImage,
  },
  {
    id: "cao-thu-ha",
    name: { en: "Dr. Cao Thu Ha", vi: "Bác sĩ Cao Thu Hà" },
    role: { en: "Pediatrician", vi: "Bác sĩ Nhi khoa" },
    specialty: { en: "Pediatrics", vi: "Nhi khoa" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: mattiasLarssonImage,
  },
  {
    id: "li-wei",
    name: { en: "Dr. Li Wei", vi: "Bác sĩ Li Wei" },
    role: { en: "Dermatologist", vi: "Bác sĩ Da liễu" },
    specialty: { en: "Dermatology", vi: "Da liễu" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Chinese", vi: "Trung Quốc" },
    languages: {
      en: "Mandarin, English, Vietnamese",
      vi: "Tiếng Trung, Tiếng Anh, Tiếng Việt",
    },
    image: rafiKotImage,
  },
  {
    id: "bui-van-hung",
    name: { en: "Dr. Bui Van Hung", vi: "Bác sĩ Bùi Văn Hùng" },
    role: { en: "Orthopedic Specialist", vi: "Chuyên gia Chỉnh hình" },
    specialty: { en: "Orthopedics", vi: "Chỉnh hình" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: mattiasLarssonImage,
  },
  {
    id: "ly-cam-nhung",
    name: { en: "Dr. Ly Cam Nhung", vi: "Bác sĩ Lý Cẩm Nhung" },
    role: { en: "Ophthalmologist", vi: "Bác sĩ Nhãn khoa" },
    specialty: { en: "Ophthalmology", vi: "Nhãn khoa" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: {
      en: "Vietnamese, English, French",
      vi: "Tiếng Việt, Tiếng Anh, Tiếng Pháp",
    },
    image: rafiKotImage,
  },
  {
    id: "arthur-pendleton",
    name: { en: "Dr. Arthur Pendleton", vi: "Bác sĩ Arthur Pendleton" },
    role: { en: "Neurology Consultant", vi: "Cố vấn Thần kinh học" },
    specialty: { en: "Neurology", vi: "Thần kinh" },
    location: { en: "Da Nang", vi: "Đà Nẵng" },
    nationality: { en: "American", vi: "Mỹ" },
    languages: { en: "English", vi: "Tiếng Anh" },
    image: mattiasLarssonImage,
  },
  {
    id: "ha-kien-quoc",
    name: { en: "Dr. Ha Kien Quoc", vi: "Bác sĩ Hà Kiến Quốc" },
    role: { en: "General Physician", vi: "Bác sĩ Đa khoa" },
    specialty: { en: "General Medicine", vi: "Y học tổng quát" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: rafiKotImage,
  },
  {
    id: "khuat-thi-lien",
    name: { en: "Dr. Khuat Thi Lien", vi: "Bác sĩ Khuất Thị Liên" },
    role: { en: "Telehealth Specialist", vi: "Chuyên gia Y tế từ xa" },
    specialty: { en: "Telemedicine", vi: "Y tế từ xa" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: {
      en: "Vietnamese, English, German",
      vi: "Tiếng Việt, Tiếng Anh, Tiếng Đức",
    },
    image: mattiasLarssonImage,
  },
  {
    id: "vuong-gia-huy",
    name: { en: "Dr. Vuong Gia Huy", vi: "Bác sĩ Vương Gia Huy" },
    role: { en: "Cardiologist", vi: "Bác sĩ Tim mạch" },
    specialty: { en: "Cardiology", vi: "Tim mạch" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: rafiKotImage,
  },
  {
    id: "ngo-bao-tran",
    name: { en: "Dr. Ngo Bao Tran", vi: "Bác sĩ Ngô Bảo Trân" },
    role: { en: "Pediatrician", vi: "Bác sĩ Nhi khoa" },
    specialty: { en: "Pediatrics", vi: "Nhi khoa" },
    location: { en: "Da Nang", vi: "Đà Nẵng" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: mattiasLarssonImage,
  },
  {
    id: "marco-ferri",
    name: { en: "Dr. Marco Ferri", vi: "Bác sĩ Marco Ferri" },
    role: { en: "Dermatologist", vi: "Bác sĩ Da liễu" },
    specialty: { en: "Dermatology", vi: "Da liễu" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "Italian", vi: "Ý" },
    languages: { en: "Italian, English", vi: "Tiếng Ý, Tiếng Anh" },
    image: rafiKotImage,
  },
  {
    id: "mai-trong-nghia",
    name: { en: "Dr. Mai Trong Nghia", vi: "Bác sĩ Mai Trọng Nghĩa" },
    role: { en: "Orthopedic Surgeon", vi: "Phẫu thuật viên Chỉnh hình" },
    specialty: { en: "Orthopedics", vi: "Chỉnh hình" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: mattiasLarssonImage,
  },
  {
    id: "luu-thu-thuy",
    name: { en: "Dr. Luu Thu Thuy", vi: "Bác sĩ Lưu Thu Thuỷ" },
    role: { en: "Ophthalmologist", vi: "Bác sĩ Nhãn khoa" },
    specialty: { en: "Ophthalmology", vi: "Nhãn khoa" },
    location: { en: "Ho Chi Minh City", vi: "Hồ Chí Minh" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: {
      en: "Vietnamese, English, French",
      vi: "Tiếng Việt, Tiếng Anh, Tiếng Pháp",
    },
    image: rafiKotImage,
  },
  {
    id: "ngo-quang-linh",
    name: { en: "Dr. Ngo Quang Linh", vi: "Bác sĩ Ngô Quang Linh" },
    role: { en: "Neurologist", vi: "Bác sĩ Thần kinh" },
    specialty: { en: "Neurology", vi: "Thần kinh" },
    location: { en: "Hanoi", vi: "Hà Nội" },
    nationality: { en: "Vietnamese", vi: "Việt Nam" },
    languages: { en: "Vietnamese, English", vi: "Tiếng Việt, Tiếng Anh" },
    image: mattiasLarssonImage,
  },
];

export const doctorsContent = {
  title: { en: "FMP DOCTORS", vi: "BÁC SĨ FMP" },
  description: {
    en: "Meet experienced doctors and find the right specialist for your next visit.",
    vi: "Tìm hiểu đội ngũ bác sĩ giàu kinh nghiệm và lựa chọn chuyên gia phù hợp cho lần khám tiếp theo.",
  },
  searchPlaceholder: {
    en: "Condition, treatment, doctor or area of interest",
    vi: "Tình trạng, điều trị, bác sĩ hoặc lĩnh vực quan tâm",
  },
  search: { en: "SEARCH", vi: "TÌM KIẾM" },
  allSpecialties: { en: "Specialty", vi: "Chuyên khoa" },
  allLocations: { en: "Location", vi: "Địa điểm" },
  nationality: { en: "Nationality", vi: "Quốc tịch" },
  languages: { en: "Languages", vi: "Ngôn ngữ" },
  viewProfile: { en: "View profile", vi: "Xem hồ sơ" },
};
