import type { TrangCaNhanResponse } from "@/types/booking.type";

export const MOCK_DASHBOARD: TrangCaNhanResponse = {
  hoSo: {
    trangThaiLienKet: "DA_LIEN_KET",
    cccd: "079203012345",
    hoTen: "Nguyễn Văn An",
    ngaySinh: "1990-05-20",
    gioiTinh: "NAM",
    soDienThoai: "0912 345 678",
    diaChi: "123 Nguyễn Trãi, Quận 1, TP. Hồ Chí Minh",
    soBaoHiemYTe: "SV4010027483901",
    tienSuBenhLy: "Tăng huyết áp độ 1 (phát hiện 2021). Dị ứng với Penicillin.",
  },
  emailTaiKhoan: "nguyenvanan@gmail.com",
  nguoiThan: [
    {
      id: 1,
      hoTen: "Nguyễn Thị Bình",
      ngaySinh: "1960-03-12",
      gioiTinh: "NU",
      cccd: "079160001234",
      soDienThoai: "0908 111 222",
      email: null,
      diaChi: "123 Nguyễn Trãi, Quận 1, TP. Hồ Chí Minh",
      soBaoHiemYTe: "GD4010027483902",
      nguoiGiamHo: null,
      lanDungCuoi: "2026-10-09T14:20:00Z",
    },
    {
      id: 2,
      hoTen: "Nguyễn Bảo Long",
      ngaySinh: "2018-07-15",
      gioiTinh: "NAM",
      cccd: null,
      soDienThoai: "0912 345 678",
      email: null,
      diaChi: "123 Nguyễn Trãi, Quận 1, TP. Hồ Chí Minh",
      soBaoHiemYTe: "TE4010027483903",
      nguoiGiamHo: {
        hoTen: "Nguyễn Văn An",
        quanHe: "CHA",
        soDienThoai: "0912 345 678",
        cccd: "079203012345",
        ngaySinh: "1990-05-20",
      },
      lanDungCuoi: "2026-08-23T11:00:00Z",
    },
    {
      id: 3,
      hoTen: "Nguyễn Thị Mai",
      ngaySinh: "1992-11-25",
      gioiTinh: "NU",
      cccd: "079192004567",
      soDienThoai: "0938 444 555",
      email: "mai.nguyen@gmail.com",
      diaChi: "123 Nguyễn Trãi, Quận 1, TP. Hồ Chí Minh",
      soBaoHiemYTe: "DN4010027483904",
      nguoiGiamHo: null,
      lanDungCuoi: "2026-07-10T10:00:00Z",
    },
  ],
  lichSapToi: {
    cuaToi: [
      {
        maPhieuKham: "PK-20261018-001",
        maTraCuu: "TC-LAN-01",
        linkPhieuKham: "/phieu-kham/PK-20261018-001",
        trangThai: "DA_XAC_NHAN",
        soThuTu: 1,
        ngay: "2026-10-18",
        gioKhamDuKien: "09:30",
        gioBatDauKhung: "09:00",
        gioKetThucKhung: "10:00",
        bacSi: {
          id: 1,
          hoTen: "BS. Trần Thị Lan",
          hocVi: "Bác sĩ Chuyên khoa 1",
          anhDaiDien: null,
        },
        tenChuyenKhoa: "Nội tổng quát",
        phongKham: {
          id: 101,
          tenPhong: "Phòng khám Đa khoa Gia Định",
          tang: "Tầng 2",
        },
        hoTenBenhNhan: "Nguyễn Văn An",
        laBanThan: true,
        hoTenNguoiGiamHo: null,
        lyDoKham: "Khám sức khỏe tổng quát",
        ngayDat: "2026-10-10T08:00:00Z",
        nguoiDat: "TOI",
        thongTinKhacHoSo: false,
        lyDoHuy: null,
        duocHuyDoi: true,
        hanHuyDoi: "2026-10-17T17:00:00Z",
        canDoiLich: false,
      },
      {
        maPhieuKham: "PK-20261022-002",
        maTraCuu: "TC-NAM-02",
        linkPhieuKham: "/phieu-kham/PK-20261022-002",
        trangThai: "CHO_XAC_NHAN",
        soThuTu: 2,
        ngay: "2026-10-22",
        gioKhamDuKien: "14:00",
        gioBatDauKhung: "13:30",
        gioKetThucKhung: "14:30",
        bacSi: {
          id: 2,
          hoTen: "BS.CK2 Lê Hoàng Nam",
          hocVi: "Bác sĩ Chuyên khoa 2",
          anhDaiDien: null,
        },
        tenChuyenKhoa: "Tim mạch",
        phongKham: {
          id: 102,
          tenPhong: "Bệnh viện Chợ Rẫy",
          tang: "Tầng 3",
        },
        hoTenBenhNhan: "Nguyễn Thị Bình (Mẹ)",
        laBanThan: false,
        hoTenNguoiGiamHo: "Nguyễn Văn An",
        lyDoKham: "Kiểm tra huyết áp định kỳ",
        ngayDat: "2026-10-09T14:20:00Z",
        nguoiDat: "TOI",
        thongTinKhacHoSo: true,
        lyDoHuy: null,
        duocHuyDoi: true,
        hanHuyDoi: "2026-10-21T17:00:00Z",
        canDoiLich: false,
      },
    ],
    cuaNguoiKhac: [],
  },
  lanKhamGanDay: [
    {
      lichHen: {
        maPhieuKham: "PK-20260910-003",
        maTraCuu: "TC-TUAN-03",
        linkPhieuKham: "/phieu-kham/PK-20260910-003",
        trangThai: "DA_HOAN_THANH",
        soThuTu: 5,
        ngay: "2026-09-10",
        gioKhamDuKien: "10:00",
        gioBatDauKhung: "09:30",
        gioKetThucKhung: "10:30",
        bacSi: {
          id: 3,
          hoTen: "BS. Phạm Anh Tuấn",
          hocVi: "Thạc sĩ Bác sĩ",
          anhDaiDien: null,
        },
        tenChuyenKhoa: "Da liễu",
        phongKham: {
          id: 103,
          tenPhong: "Phòng khám Da liễu Trung ương",
          tang: "Tầng 1",
        },
        hoTenBenhNhan: "Nguyễn Văn An",
        laBanThan: true,
        hoTenNguoiGiamHo: null,
        lyDoKham: "Viêm da cơ địa",
        ngayDat: "2026-09-05T09:00:00Z",
        nguoiDat: "TOI",
        thongTinKhacHoSo: false,
        lyDoHuy: null,
        duocHuyDoi: false,
        hanHuyDoi: "2026-09-09T17:00:00Z",
        canDoiLich: false,
      },
      ketQua: {
        chanDoan: "Viêm da tiếp xúc dị ứng",
        ghiChu: "Tránh tiếp xúc xà phòng thơm và hóa chất.",
        ngayTaiKhamDeXuat: "2026-10-10",
        donThuoc: [
          {
            tenThuoc: "Fucicort Cream 15g",
            donVi: "Tuýp",
            lieuDung: "Bôi ngày 2 lần",
            soLanMoiNgay: 2,
            soNgayDung: 7,
            ghiChuSuDung: "Bôi mỏng vùng da thương tổn",
          },
        ],
      },
    },
    {
      lichHen: {
        maPhieuKham: "PK-20260825-004",
        maTraCuu: "TC-CHAU-04",
        linkPhieuKham: "/phieu-kham/PK-20260825-004",
        trangThai: "DA_HOAN_THANH",
        soThuTu: 3,
        ngay: "2026-08-25",
        gioKhamDuKien: "08:00",
        gioBatDauKhung: "07:30",
        gioKetThucKhung: "08:30",
        bacSi: {
          id: 4,
          hoTen: "BS. Đỗ Minh Châu",
          hocVi: "Bác sĩ Chuyên khoa 1",
          anhDaiDien: null,
        },
        tenChuyenKhoa: "Nhi khoa",
        phongKham: {
          id: 104,
          tenPhong: "Bệnh viện Nhi Đồng 1",
          tang: "Tầng 2",
        },
        hoTenBenhNhan: "Nguyễn Bảo Long (Con)",
        laBanThan: false,
        hoTenNguoiGiamHo: "Nguyễn Văn An",
        lyDoKham: "Viêm phế quản cấp",
        ngayDat: "2026-08-23T11:00:00Z",
        nguoiDat: "TOI",
        thongTinKhacHoSo: true,
        lyDoHuy: null,
        duocHuyDoi: false,
        hanHuyDoi: "2026-08-24T17:00:00Z",
        canDoiLich: false,
      },
      ketQua: {
        chanDoan: "Viêm đường hô hấp trên",
        ghiChu: "Uống nhiều nước ấm, theo dõi thân nhiệt.",
        ngayTaiKhamDeXuat: null,
        donThuoc: [],
      },
    },
    {
      lichHen: {
        maPhieuKham: "PK-20260801-006",
        maTraCuu: "TC-DAT-06",
        linkPhieuKham: "/phieu-kham/PK-20260801-006",
        trangThai: "DA_HOAN_THANH",
        soThuTu: 4,
        ngay: "2026-08-01",
        gioKhamDuKien: "09:00",
        gioBatDauKhung: "08:30",
        gioKetThucKhung: "09:30",
        bacSi: {
          id: 6,
          hoTen: "BS. Ngô Thành Đạt",
          hocVi: "Thạc sĩ Bác sĩ",
          anhDaiDien: null,
        },
        tenChuyenKhoa: "Tai - Mũi - Họng",
        phongKham: {
          id: 106,
          tenPhong: "Phòng khám Tai Mũi Họng Sài Gòn",
          tang: "Tầng 1",
        },
        hoTenBenhNhan: "Nguyễn Văn An",
        laBanThan: true,
        hoTenNguoiGiamHo: null,
        lyDoKham: "Ù tai và đau họng",
        ngayDat: "2026-07-28T09:00:00Z",
        nguoiDat: "TOI",
        thongTinKhacHoSo: false,
        lyDoHuy: null,
        duocHuyDoi: false,
        hanHuyDoi: "2026-07-31T17:00:00Z",
        canDoiLich: false,
      },
      ketQua: {
        chanDoan: "Viêm họng hạt cấp tính",
        ghiChu: "Súc họng nước muối sinh lý.",
        ngayTaiKhamDeXuat: null,
        donThuoc: [],
      },
    },
  ],
  soLich: {
    sapToiCuaToi: 2,
    sapToiCuaNguoiKhac: 0,
    lichSu: 12,
    daKham: 9,
  },
};
