import type { LichHenCuaToiResponse } from "@/types/booking.type";

export const MOCK_APPOINTMENTS: LichHenCuaToiResponse[] = [
  {
    maPhieuKham: "PK-20261018-001",
    maTraCuu: "TC-LAN-01",
    linkPhieuKham: "/phieu-kham/PK-20261018-001",
    trangThai: "DA_XAC_NHAN",
    soThuTu: 1,
    ngay: "2026-10-18",
    gioKhamDuKien: "09:30",
    gioBatDauKhung: "09:00",
    gioKetThucKhung: "10:00",
    bacSi: {
      id: 1,
      hoTen: "BS. Trần Thị Lan",
      hocVi: "Bác sĩ Chuyên khoa 1",
      anhDaiDien: null,
    },
    tenChuyenKhoa: "Nội tổng quát",
    phongKham: {
      id: 101,
      tenPhong: "Phòng khám Đa khoa Gia Định",
      tang: "Tầng 2",
    },
    hoTenBenhNhan: "Nguyễn Văn An",
    laBanThan: true,
    hoTenNguoiGiamHo: null,
    lyDoKham: "Kiểm tra sức khỏe định kỳ",
    ngayDat: "2026-10-10T08:00:00Z",
    nguoiDat: "TOI",
    thongTinKhacHoSo: false,
    lyDoHuy: null,
    duocHuyDoi: true,
    hanHuyDoi: "2026-10-17T17:00:00Z",
    canDoiLich: false,
  },
  {
    maPhieuKham: "PK-20261022-002",
    maTraCuu: "TC-NAM-02",
    linkPhieuKham: "/phieu-kham/PK-20261022-002",
    trangThai: "CHO_XAC_NHAN",
    soThuTu: 2,
    ngay: "2026-10-22",
    gioKhamDuKien: "14:00",
    gioBatDauKhung: "13:30",
    gioKetThucKhung: "14:30",
    bacSi: {
      id: 2,
      hoTen: "BS.CK2 Lê Hoàng Nam",
      hocVi: "Bác sĩ Chuyên khoa 2",
      anhDaiDien: null,
    },
    tenChuyenKhoa: "Tim mạch",
    phongKham: {
      id: 102,
      tenPhong: "Bệnh viện Chợ Rẫy",
      tang: "Tầng 3",
    },
    hoTenBenhNhan: "Nguyễn Thị Bình (Mẹ)",
    laBanThan: false,
    hoTenNguoiGiamHo: "Nguyễn Văn An",
    lyDoKham: "Tái khám tăng huyết áp",
    ngayDat: "2026-10-09T14:20:00Z",
    nguoiDat: "TOI",
    thongTinKhacHoSo: true,
    lyDoHuy: null,
    duocHuyDoi: true,
    hanHuyDoi: "2026-10-21T17:00:00Z",
    canDoiLich: false,
  },
  {
    maPhieuKham: "PK-20260910-003",
    maTraCuu: "TC-TUAN-03",
    linkPhieuKham: "/phieu-kham/PK-20260910-003",
    trangThai: "DA_HOAN_THANH",
    soThuTu: 5,
    ngay: "2026-09-10",
    gioKhamDuKien: "10:00",
    gioBatDauKhung: "09:30",
    gioKetThucKhung: "10:30",
    bacSi: {
      id: 3,
      hoTen: "BS. Phạm Anh Tuấn",
      hocVi: "Thạc sĩ Bác sĩ",
      anhDaiDien: null,
    },
    tenChuyenKhoa: "Da liễu",
    phongKham: {
      id: 103,
      tenPhong: "Phòng khám Da liễu Trung ương",
      tang: "Tầng 1",
    },
    hoTenBenhNhan: "Nguyễn Văn An",
    laBanThan: true,
    hoTenNguoiGiamHo: null,
    lyDoKham: "Dị ứng mẩn đỏ vùng tay",
    ngayDat: "2026-09-05T09:00:00Z",
    nguoiDat: "TOI",
    thongTinKhacHoSo: false,
    lyDoHuy: null,
    duocHuyDoi: false,
    hanHuyDoi: "2026-09-09T17:00:00Z",
    canDoiLich: false,
  },
  {
    maPhieuKham: "PK-20260825-004",
    maTraCuu: "TC-CHAU-04",
    linkPhieuKham: "/phieu-kham/PK-20260825-004",
    trangThai: "DA_HOAN_THANH",
    soThuTu: 3,
    ngay: "2026-08-25",
    gioKhamDuKien: "08:00",
    gioBatDauKhung: "07:30",
    gioKetThucKhung: "08:30",
    bacSi: {
      id: 4,
      hoTen: "BS. Đỗ Minh Châu",
      hocVi: "Bác sĩ Chuyên khoa 1",
      anhDaiDien: null,
    },
    tenChuyenKhoa: "Nhi khoa",
    phongKham: {
      id: 104,
      tenPhong: "Bệnh viện Nhi Đồng 1",
      tang: "Tầng 2",
    },
    hoTenBenhNhan: "Nguyễn Bảo Long (Con)",
    laBanThan: false,
    hoTenNguoiGiamHo: "Nguyễn Văn An",
    lyDoKham: "Sốt cao và ho có đờm",
    ngayDat: "2026-08-23T11:00:00Z",
    nguoiDat: "TOI",
    thongTinKhacHoSo: true,
    lyDoHuy: null,
    duocHuyDoi: false,
    hanHuyDoi: "2026-08-24T17:00:00Z",
    canDoiLich: false,
  },
  {
    maPhieuKham: "PK-20260905-005",
    maTraCuu: "TC-HUY-05",
    linkPhieuKham: "/phieu-kham/PK-20260905-005",
    trangThai: "DA_HUY",
    soThuTu: 7,
    ngay: "2026-09-05",
    gioKhamDuKien: "15:30",
    gioBatDauKhung: "15:00",
    gioKetThucKhung: "16:00",
    bacSi: {
      id: 5,
      hoTen: "BS. Vũ Quang Huy",
      hocVi: "Bác sĩ Chuyên khoa 2",
      anhDaiDien: null,
    },
    tenChuyenKhoa: "Xương khớp",
    phongKham: {
      id: 105,
      tenPhong: "Phòng khám Chấn thương Chỉnh hình",
      tang: "Tầng 1",
    },
    hoTenBenhNhan: "Nguyễn Văn An",
    laBanThan: true,
    hoTenNguoiGiamHo: null,
    lyDoKham: "Đau mỏi vai gáy",
    ngayDat: "2026-09-01T10:00:00Z",
    nguoiDat: "TOI",
    thongTinKhacHoSo: false,
    lyDoHuy: "Bận công tác đột xuất",
    duocHuyDoi: false,
    hanHuyDoi: "2026-09-04T17:00:00Z",
    canDoiLich: false,
  },
];
